First-Peoples-Cultural-Council/fv-web

.eslintrc.js
.github/workflows/CypressTests.yml
.gitignore
browserstack.json
cypress.config.js
cypress/e2e/FirstVoicesDev/dashboard/create_page.cy.js
cypress/e2e/FirstVoicesDev/homepage.cy.js
cypress/e2e/FirstVoicesDev/kids.cy.js
cypress/e2e/FirstVoicesDev/login/immersion.cy.js
cypress/e2e/FirstVoicesDev/login/login.cy.js
cypress/e2e/FirstVoicesDev/login/widgets.cy.js
cypress/e2e/FirstVoicesDev/navigation.cy.js
cypress/e2e/FirstVoicesDev/phrases.cy.js
cypress/e2e/FirstVoicesDev/search.cy.js
cypress/e2e/FirstVoicesDev/songs.cy.js
cypress/e2e/FirstVoicesDev/stories.cy.js
cypress/e2e/FirstVoicesDev/viewport.cy.js
cypress/e2e/FirstVoicesDev/word.cy.js
cypress/env/.gitignore
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/e2e.js
package-lock.json
package.json

Fw-4288 Add Cypress tests

---

cypress/e2e/dashboard/alpha.cy.js
cypress/e2e/navigation.cy.js
sonar-project.properties

Reduce scope of Sonar to only include src

---

src/components/DictionaryGridTile/DictionaryGridTilePresentationKids.js

FW-3868 Kids words link

---

README.md
package-lock.json
package.json
public/index.html
src/GlobalConfiguration.js
src/services/config.js
webpack/webpack.development.js
webpack/webpack.proxied.preprod.js
webpack/webpack.skaffold.js

Update port and var

---

src/components/Actions/QrcodeModalContent.js
src/components/Actions/ShareButton.js
src/components/Alphabet/AlphabetData.js
src/components/Alphabet/AlphabetPresentationSelected.js
src/components/Alphabet/AlphabetPresentationWidget.js
src/components/AppNavBar/AppNavBarPresentation.js
src/components/AudioButton/AudioButton.js
src/components/AudioMinimal/AudioMinimalPresentation.js
src/components/AudioNative/AudioNative.js
src/components/Audiobar/AudiobarPresentation.js
src/components/ByCategory/ByCategoryPresentation.js
src/components/Categories/CategoriesPresentation.js
src/components/CategoriesBrowser/CategoriesBrowserPresentation.js
src/components/ConditionsOfUse/ConditionsOfUsePresentation.js
src/components/ConfirmationDialog/ConfirmationDialogPresentation.js

Fw 4361 lint errors

---

src/components/Audiobar/AudiobarPresentation.js
src/components/ShareLinks/ShareLinksPresentation.js

FW-4089-copy-toast

---

src/index.js

FW-3913-useQuery

---

src/common/dataHooks/useMySites.js
src/common/dataHooks/useSites.js
src/components/Languages/LanguagesData.js
src/components/Languages/LanguagesPresentation.js
src/services/api/site.js

Fw 4453 fe my sites api hookup

---

src/common/constants/directories.js
src/common/constants/index.js
src/common/dataHooks/useImmersion.js
src/common/dataHooks/useSite.js
src/components/Home/HomeContainer.js
src/components/Site/SiteData.js
src/context/SiteContext.js
src/services/api/site.js

FW-4469 use sites single api

---

src/common/constants/paths.js
src/common/dataHooks/useAlphabet.js
src/components/Alphabet/AlphabetContainer.js
src/components/Alphabet/AlphabetData.js
src/components/Alphabet/AlphabetPresentation.js
src/components/Alphabet/AlphabetPresentationSelected.js
src/services/api/characters.js
src/services/api/index.js

FW-4480 use characters read api

---

src/common/dataHooks/useMySites.js

Update data hook to match the updated my-sites api:
* standard paginated list response
* added role field
N/A

fw-4550, handle updated my-sites api

---

src/components/Alphabet/AlphabetPresentationSelected.js
src/components/AudioButton/AudioButton.js
src/components/Audiobar/AudiobarData.js
src/components/Audiobar/AudiobarPresentation.js
src/components/DictionaryList/DictionaryListPresentation.js
src/context/AudiobarContext.js

 FW-4544 Update AudioBar and Audiobutton for new data format

---

src/common/constants/paths.js
src/common/dataAdaptors/index.js
src/common/dataAdaptors/widgetAdaptors.js
src/common/dataHooks/usePage.js
src/common/dataHooks/usePages.js
src/common/dataHooks/useSite.js
src/common/dataHooks/useWidget.js
src/common/dataHooks/useWidgets.js
src/common/utils/urlHelpers.js
src/components/DashboardPages/DashboardPagesData.js
src/components/DashboardWidgets/DashboardWidgetsPresentation.js
src/components/Home/HomeContainer.js
src/components/Home/HomeData.js
src/components/Page/PageContainer.js
src/components/Page/PageData.js
src/components/PageBanner/PageBannerPresentation.js
src/components/Resource/ResourceContainer.js
src/components/Resource/ResourceData.js
src/components/Resource/ResourcePresentation.js
src/components/Site/SiteFrame.js
src/components/Widget/WidgetContainer.js
src/components/Widget/WidgetData.js
src/components/WidgetArea/WidgetAreaContainer.js
src/components/WidgetAreaEdit/WidgetAreaEditPresentationSettingsPane.js
src/components/WidgetTextConcise/WidgetTextConcisePresentation.js
src/services/api/index.js
src/services/api/pages.js

FW-4493 use pages read api

---

src/common/utils/widgetHelpers.js

FW-4522 Hide gallery widget

---

src/components/MediaCrud/UploadAudio.js
src/components/MediaDetails/MediaDetailsAudio.js
src/services/api/media.js

- Added a upload audio endpoint
- Refactored UploadAudio.js to use new endpoint
- Updated media details to display media details from new BE.
N/A

FW-4507 use Audio Create + Read APIs

---

src/components/App/AppData.js
src/components/AppNavBar/AppNavBarPresentation.js
src/components/Dashboard/DashboardPresentation.js
src/components/DashboardHome/DashboardHomePresentation.js
src/components/NavBar/NavBarPresentationMobile.js
src/components/UserMenu/UserMenuPresentation.js
src/context/UserContext.js

* update our id token info to match the prod user pool, which has different required fields than the pool we've been using for development
* this includes fallbacks for all relevant oidc standard claims, so this should keep working under most circumstances
* changed our UserContext to provide fullName and displayName instead of displayName (meaning full name) and firstName, to match our end goal for names
N/A

fw-4691, prod-like user pool

---

src/components/Languages/LanguagesContainer.js
src/components/Languages/LanguagesPresentation.js
src/components/Languages/SiteCard.js

Re-enabled private sites modal.
N/A

Fw 4684 private sites modal not popping up

---

src/components/LandingBanner/LandingBannerData.js

FW-4709-hide-search-link

---

src/common/dataAdaptors/widgetAdaptors.js
src/common/dataHooks/useCategories.js
src/common/dataHooks/useWidgets.js
src/components/Form/AddMedia.js
src/components/WidgetCrud/WidgetCrudContainer.js
src/components/WidgetCrud/WidgetCrudData.js
src/components/WidgetCrud/WidgetCrudPresentation.js
src/components/WidgetCrud/WidgetFormBase.js
src/components/WidgetCrud/WidgetFormText.js
src/components/WidgetCrud/WidgetFormTextConcise.js
src/services/api/widgets.js

- Updated WidgetCrud components to allow for widgets to be created/updated/deleted.
N/A

Fw 4512 use widgets create update delete ap is

---

src/components/StoryCrud/StoryCrudContainer.js
src/components/WidgetAreaEdit/WidgetAreaEditPresentationSettingsPane.js

fw-4725, hide standalone visibility selectors

---

src/components/Alphabet/AlphabetContainer.js
src/components/Alphabet/AlphabetData.js
src/components/Categories/CategoriesContainer.js
src/components/Categories/CategoriesData.js
src/components/Categories/CategoriesPresentation.js
src/components/Dashboard/DashboardData.js
src/components/DashboardEdit/DashboardEditData.js
src/components/DashboardHome/DashboardHomePresentation.js

- Remove outdated Dashboard message re editing in V1
- Remove dictionary type selector from Categories page
- Add dictionary create tiles to Dashboard homepage for Editors and Assistants
- Fix character click issue in widget view
N/A

FW-4711 alphabet widget not clickable

---

src/components/DashboardCreate/DashboardCreateContainer.js
src/components/DashboardCreate/DashboardCreateData.js
src/components/DashboardEdit/DashboardEditContainer.js
src/components/DashboardEdit/DashboardEditData.js

Restricted story and songs routes and tiles to super_admin only
N/A

FW-4726 Hide songs + stories CRUD in the dashboard

---

src/components/NavBar/NavBarPresentation.js

added link to FV landing page

---

src/components/Song/SongPresentation.js
src/components/Song/SongPresentationDrawer.js
src/components/SongsAndStories/SongsAndStoriesPresentation.js

FW-4728-SongsLoadPlay

---

src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js

FW-4102-DictionaryAcknowledgementToggle

---

src/common/icons/Login.js
src/components/AppNavBar/AppNavBarPresentation.js
src/components/LandingBanner/LandingBannerPresentation.js

- Replace login icon with one of equal size
- prevent navbar labels from wrapping
- small sonarlint refactor of LandingBanner - code change only
N/A

FW-4708 app nav bar

---

src/common/dataAdaptors/categoriesAdaptors.js
src/common/dataHooks/useCategories.js
src/common/dataHooks/usePages.js
src/components/Page/PageContainer.js
src/components/Page/PageData.js
src/components/PageBanner/PageBannerPresentation.js
src/components/Site/SiteFrame.js
src/services/api/categories.js
src/services/api/pages.js
src/services/api/site.js

- fixed param checking in PageData and Resources
- fix css for logo on custom pages
- fix syntax of returns in api services that were causing promises to be passed and errors to be missed
- created a data adaptor for constructing data to submit to apis for creating and updating categories
N/A

FW-4776 reserved name custom page bug

---

src/components/Form/MediaArrayField.js

FW-4783-dashboardAudioDoc

---

src/components/Song/SongPresentationDrawer.js

size of media object needed changing to play video from drawer
N/A

FW-4728-SongsVideo

---

src/components/MediaCrud/UploadMedia.js
src/services/api/media.js

- Media file title defaults to filename.
- used URL generator to return valid url instead of string concatenation.
N/A

Fw 4787 v 3 dashboard cant upload images video

---

src/components/PageCrud/PageCrudData.js

- Removed media objects being casted into array for incoming media objects for pagesCrudData.
N/A

Fw 4789 v 3 site custom page doesnt display banner

---

src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/MediaDetails/MediaDetailsVisual.js

media drawer titles in dashboard are properly capitalized and the info icon for media is more clickable
N/A

Fw 4792 dashboard titles & FW-4718 -info icon

---

src/common/utils/getIcon.js
src/components/CategoryCrud/CategoryCrudPresentation.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js

FW-4817 creating a phrase saves as a word

---

src/common/constants/roles.js
src/components/App/AppContainer.js
src/components/Dashboard/DashboardData.js
src/components/MediaDetails/MediaDetailsVisual.js
src/components/NavBar/NavBarPresentationMenu.js
src/components/UserMenu/UserMenuData.js
src/components/UserMenu/UserMenuPresentation.js
src/context/UserContext.js

- remove direct dashboard route without site slug
- Add function for generating dashboard link for user menu which returns the current site if the user is a team member or the first site from the users roles that they are a team member of
- allow for staff access in the future after FW-4694
N/A

FW-4822 link to dashboard bug

---

src/components/Alphabet/AlphabetPresentationSelected.js
src/components/Song/SongPresentationDrawer.js
src/components/WidgetAreaEdit/WidgetAreaEditPresentationSettingsPane.js
src/components/WidgetLogo/WidgetLogoPresentation.js

- FW-4850 fixed bug where broken video tag displayed when no video present in data
- FW-4788 Fixed link to edit widget from Homepage and Custom Page settings pane
- FW-4853 restored "Right" format recognition for Logo widget
- FW-4739 Alphabet translation fixes
N/A

FW-4788, FW-4853, FW-4850, FW-4739 Song drawer video fix

---

src/common/dataAdaptors/siteAdaptors.js
src/common/dataHooks/useCharacters.js
src/components/Dashboard/DashboardPresentationSiteSelect.js
src/components/Form/TextField.js
src/components/Languages/SiteCard.js
src/services/api/characters.js

- Fix site select menu on dashboard so that it displays logos.
- Make reusable site logo data adaptor
- Prevent the enter key from submitting forms from TextField
N/A

FW-4874, FW-4147, Dashboard logos and character edit form bug

---

src/components/Song/SongPresentation.js

fw-4851, show intro translation on song detail page

---

src/common/dataAdaptors/songAdaptors.js
src/components/Song/SongPresentation.js
src/components/Story/StoryPresentation.js

* add Notes section on Song detail page, and change Acknowledgements display to match
* add Acknowledgements and Notes sections on Story detail page
* used the same styling for each (based on original Song Introduction header)
* put some css classes in reusable variables
N/A

Fw-4851, notes and acks on songs and stories

---

src/components/MediaCrud/MediaCrudContainer.js

Added conditional scrollbar to media crud component.
N/A

Fw 4101 image upload button is not visible on certain resolutions with default zoom

---

src/common/hooks/useSearchBox.js
src/common/hooks/useSearchBoxNavigation.js
src/common/hooks/useSearchLanguage.js
src/common/hooks/useSearchModal.js
src/common/hooks/useSearchTerm.js
src/common/hooks/useSearchType.js

Fixed bug where search input could not be cleared using backspace/delete
N/A

FW-4841 search not clearing

---

src/common/dataAdaptors/storyAdaptors.js

* Handle any errors that happen while constructing the page text preview (used in the story edit forms)
N/A

fw-4920, handle invalid wysiwyg data in story pages

---

src/common/dataHooks/useMutationWithNotification.js
src/common/utils/validationHelpers.js
src/components/App/AppContainer.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js
src/components/Languages/LanguagesContainer.js
src/components/Languages/LanguagesData.js

- Add Helmet to App parent component to ensure window title returns to "FirstVoices" after visiting a custom page
- Add Loading animation to Languages page while fetching languages
- Match text char limits for Dictionary Entries to BE
- Make error message for maxChar limit validation more readable
N/A

FW-4839, FW-4193, FW-4249, FW-4887 bug fixes

---

src/common/utils/validationHelpers.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/ImageWithLightbox/ImageWithLightboxPresentation.js
src/components/LandingBanner/LandingBannerData.js

max character for widget name
word drawer image cursor fix
typo on landing page
N/A

Fw 4869 typo global homepage, etc

---

src/common/constants/visibility.js
src/common/dataAdaptors/siteAdaptors.js
src/components/Languages/SiteCard.js

- update visibility constants to match new API response visibility values (all lowercase)
- remove fudging of previous values
N/A

Visibility update to match BE

---

src/components/Form/WysiwygField.js
src/components/WysiwygBlock/WysiwygBlock.js

Ensure state is updated on button click
N/A

FW-4858 Ensure state is updated on button click

---

src/common/dataHooks/usePages.js
src/components/Alphabet/AlphabetContainer.js
src/components/Alphabet/AlphabetData.js
src/components/WidgetAreaEdit/WidgetAreaEditContainer.js
src/components/WidgetAreaEdit/WidgetAreaEditData.js
src/components/WidgetAreaEdit/WidgetAreaEditPresentation.js

- ensured that a character is selected on load of the alphabet widget
- ensure Add widget modal closes after widget has been selected and added
N/A

FW-4855, FW-4856 alphabet widget and add widget modal

---

src/components/Categories/CategoriesPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js

visual improvements for mobile - dictionary detail audio button and categories buttons
N/A

Fw 2975 visual improvements

---

src/common/dataAdaptors/pageAdaptors.js
src/components/Story/StoryPresentation.js
src/components/StoryCoverCrud/StoryCoverCrudPresentation.js
src/components/StoryPagesCrud/StoryPageForm.js
src/components/WidgetCrud/WidgetFormContact.js
src/components/WidgetCrud/WidgetFormQuotes.js
src/components/WidgetCrud/WidgetFormText.js
src/components/WidgetCrud/WidgetFormTextFull.js
src/components/WidgetCrud/WidgetFormTextIcons.js

- Removed page slug from body of custom page update - was causing error
- Make text field required for - Text with Image, Page Text, Text with Icons
- Add default EditorState to forms with Wysiwyg
- Make all 3 quotes on Quotes Widget required
- remove use of ImageWithLightbox on story cover (was generating the info icon)
N/A

FW-4951, FW-4958, FW-4970 text with image widget, update page, 

---

src/common/utils/mediaHelpers.js
src/components/ByCategory/ByCategoryPresentation.js

corrected audio file size function
reduced size of categories button
N/A

Fw 4752 audio file size

---

src/components/Resource/ResourceContainer.js
src/components/Resource/ResourceData.js
src/components/Resource/ResourcePresentation.js

reformatted Resource component to account for external link behaviour
N/A

FW-4868-support-link

---

src/components/Audiobar/AudiobarPresentation.js

added parameters around audio info button so that it will not display without a title
N/A

FW-4088-sound-bar-hide-icon

---

src/components/CategoryCrud/CategoryCrudPresentation.js
src/components/CharacterCrud/CharacterCrudPresentation.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js
src/components/Form/AddMedia.js
src/components/Form/FileUploadField.js
src/components/Form/Select.js
src/components/Form/SelectOneMedia.js
src/components/Form/TextAreaField.js
src/components/Form/TextField.js
src/components/Form/WysiwygField.js
src/components/HomeCrud/HomeForm.js
src/components/ImmersionCrud/ImmersionCrudPresentation.js
src/components/MediaCrud/UploadAudio.js
src/components/PageCrud/PageForm.js
src/components/SpeakerCrud/SpeakerCrudPresentation.js
src/components/StoryCoverCrud/StoryCoverCrudPresentation.js
src/components/StoryPagesCrud/StoryPageForm.js
src/components/WidgetCrud/WidgetFormApps.js
src/components/WidgetCrud/WidgetFormBase.js
src/components/WidgetCrud/WidgetFormContact.js
src/components/WidgetCrud/WidgetFormGallery.js
src/components/WidgetCrud/WidgetFormKeyboards.js
src/components/WidgetCrud/WidgetFormLogo.js
src/components/WidgetCrud/WidgetFormQuotes.js
src/components/WidgetCrud/WidgetFormText.js
src/components/WidgetCrud/WidgetFormTextConcise.js
src/components/WidgetCrud/WidgetFormTextFull.js
src/components/WidgetCrud/WidgetFormTextIcons.js

Moved rendering of error messages into form field components to reduce duplication in forms
N/A

Refactor of form validation errors to reduce duplication

---

src/components/MediaDetails/MediaDetailsAudio.js
src/components/MediaDetails/MediaDetailsVisual.js

made audio and visual details drawer sticky to the top of the container
N/A

FW-4999-audio-details-scroll

---

package.json

This PR fixes the package.json start script for developing with a local backend.
N/A

Fix package.json local start script

---

src/common/dataHooks/useStories.js
src/components/Form/TextTranslationArrayField.js

Song Form - Fix error message bug and increase rows on lyric textarea
Story Form - fix story success message for Privacy step
N/A

FW-5046, FW-5090 create song no error message

---

public/index.html

- we had code for both the old and new site ids :-\
N/A

fw-3776, remove old tracking code

---

src/components/DictionaryCrud/DictionaryCrudPresentation.js

acknowledgments vs acknowledgements
N/A

fw-5107, fix typo in dict validator

---

src/components/NavBar/NavBarPresentation.js
src/components/Site/SiteData.js

* Move NavBar home buttons into loading container
* Ensure siteLoading is false until siteStore is ready
N/A

fw-5179, fix refresh error

---

src/components/Join/JoinForm.js
src/components/Join/JoinPresentation.js
src/components/Languages/PrivateSiteCard.js
src/components/NavBar/NavBarPresentationMobile.js
src/components/Site/SiteData.js

- Adjustments to styling to optimize join form for mobile and smaller screens
- Adjustments to PrivateSite modal message styling to optimize for mobile
- Replace deprecated isLoading in SIteData
- Reduce mobile menu item size to fit on smaller screens 
N/A

FW-5175 join for small screens

---

src/components/CategoriesBrowser/CategoriesBrowserPresentation.js

Prevent submit on enter/return keyDown in Category browser search
N/A

FW-5180 Category browser premature submit

---

src/components/AppNavBar/AppNavBarPresentation.js

made beta sign a button and added a modal with links to www.archive.firstvoices.com and hello@firstvoices.com
N/A

Fw 3856 beta sign

---

src/components/Dashboard/DashboardData.js
src/components/DashboardCreate/DashboardCreateData.js
src/components/DashboardEdit/DashboardEditData.js
src/components/DashboardHome/DashboardHomePresentation.js
src/components/MediaDetails/MediaDetailsAudio.js

sentence casing for titles on dashboard create and edit forms
N/A

FW-4857-dashboard-edits

---

src/components/AppNavBar/AppNavBarPresentation.js
src/components/LandingPage/LandingPageData.js

updated text on hard coded quotes
N/A

FW-5209-update-quotes

---

src/common/hooks/useLoginLogout.js
src/components/App/AppData.js

- remove expired tokens and proceed as anonymous user
- handle edge cases (mainly affecting devs) involving tokens from wrong user pool
N/A

fw-4800, handle expired and invalid tokens better

---

src/common/utils/validationHelpers.js
src/components/PageCrud/PageForm.js

changed character limit to 225 for subtitle
N/A

FW-5190-create-custom-page-subtitle-length

---

src/components/Alphabet/AlphabetContainer.js
src/components/ByAlphabet/ByAlphabetContainer.js
src/components/ByAlphabet/ByAlphabetData.js
src/components/ByCategory/ByCategoryContainer.js
src/components/ByCategory/ByCategoryData.js
src/components/Categories/CategoriesContainer.js
src/components/Dictionary/DictionaryContainer.js
src/components/DictionaryGrid/DictionaryGridPresentation.js
src/components/DictionaryGridTile/DictionaryGridTileContainer.js
src/components/SongsAndStories/SongsAndStoriesContainer.js

changed default value for kids from false to null for components usin…
N/A

FW-5228-v-3-site-dashboard-search-not-returning-back-expected-results

---

src/common/hooks/useSearchBoxNavigation.js
src/components/SearchSiteForm/SearchSiteFormContainer.js

- Updated kids default value in useSearchBox navigation and SearchSiteFormContainer
N/A

Fw 5228 v 3 site dashboard search not returning back expected results

---

src/components/Modal/ModalPresentation.js

removed css height property causing the scrolling bug in modal.  Tested all modals and they look good except for an existing bug in Edit Widget -> Add Audio (Media).  Reverting my change did now fix this.  Will log seperate ticket if if doesn't already exist.
N/A

Fw 5184 join request modal scroll

---

src/components/Games/GamesPresentation.js

- Added back the page to display "FirstVoices Games will return soon!"
N/A

added back games will return soon page

---

src/components/Audiobar/AudiobarPresentationMobile.js

FW-5258 Fixed a bug related to displaying of speaker names on mobile audio bar

---

src/components/App/AppContainer.js
src/components/App/LegacyRedirect.js

fw-5261, add redirect for legacy explore languages page

---

src/components/Dashboard/DashboardPresentation.js

FW-5269 fixed hrefs for dashboard sidebar links

---

src/common/constants/legacySiteMapping.js
src/components/App/AppContainer.js
src/components/App/LegacyRedirect.js

* Google search results are showing a slightly different url than is live on archive.firstvoices.com ("Eng" vs "[Eng]"), so I added an extra redirect to our list
N/A

fw-5292, additional redirect from legacy url

---

src/common/icons/PhraseScrambler.js
src/common/utils/getIcon.js
src/components/Game/GameData.js
src/components/Game/GamePresentation.js
src/components/Game/PhraseScrambler/PhraseScramblerContainer.js
src/components/Game/PhraseScrambler/PhraseScramblerData.js
src/components/Game/PhraseScrambler/PhraseScramblerPresentation.js
src/components/Game/PhraseScrambler/index.js
src/components/Game/WordScramble/index.js

- Renamed Word Scramble to Phrase Scrambler.
N/A

FW-5237 Updates to PhraseScrambler

---

src/common/dataHooks/useStories.js

- Updated url for redirection after a story is deleted
N/A

FW-5269 Updated url for redirection after a story is deleted.

---

src/components/DeleteButton/DeleteButtonPresentation.js
src/components/SpeakerCrud/SpeakerCrudPresentation.js

* add optional param to delete modal for smaller explanatory text
N/A

fw-5283, message when deleting speaker

---

src/common/utils/functionHelpers.js

- Refactored array shuffle method in function utils
N/A

Array shuffle method refactoring

---

src/common/utils/gameHelpers.js
src/components/Game/GameContainer.js
src/components/Game/GamePresentation.js
src/components/Game/PhraseScrambler/PhraseScramblerContainer.js
src/components/Game/PhraseScrambler/PhraseScramblerData.js
src/components/Game/PhraseScrambler/PhraseScramblerPresentation.js

- Get phrases from BE using the search API instead of mock data
- Added defaults for the search API to be used in game
N/A

FW-5238 Hook up PhraseScrambler with BE

---

src/components/Game/PhraseScrambler/PhraseScramblerData.js

- Added random parameter to search API for phrase scrambler game.
N/A

FW-5238 Added random parameter to PhraseScrambler game

---

src/index.js

Log global config to debug Sentry on dev deployment

---

src/components/AppNavBar/AppNavBarPresentation.js
src/components/DashboardAlphabet/DashboardAlphabetPresentation.js
src/components/DashboardLanding/DashboardLandingPresentation.js
src/components/DashboardReports/DashboardReportsContainer.js
src/components/DashboardTable/DashboardTablePresentation.js

- fixed order of links in AppNavbar
- fixed alignment of tiles on Reports page on xl screens
N/A

Misc fixes

---

src/index.js

Remove Sentry debug log

---

src/components/Game/Parachute/ParachutePresentation.js
src/components/Game/PhraseScrambler/PhraseScramblerPresentation.js

This PR updates the messages displayed on the games pages when no usable dictionary content could be found.
N/A

Update games messages when no valid dictionary content found

---

src/common/hooks/useSearchBoxNavigation.js
src/common/hooks/useSearchParamsState.js
src/common/utils/urlHelpers.js

* updated the search box navigation controller to maintain existing url params and only reset the ones it is in charge of
N/A

fw-5340, search box shouldn't clear search filters

---

src/components/DashboardEntries/DashboardEntriesContainer.js
src/components/DashboardEntries/DashboardEntriesData.js
src/components/DashboardEntries/DashboardEntriesPresentation.js

- renamed resetSearch to removeFilters
- refactored removeFilters to not reset the searchTerm, domain and types
N/A

FW-5344 added preservation of searchTerm and domain to removeFilters

---

src/common/hooks/useSearchBoxNavigation.js

- reset sort if a new search query is enetered and searched for
N/A

FW-5430 bug fix - reset sort if a search query is entered

---

src/components/AboutFV/AboutFV.js
src/components/AboutFV/index.js
src/components/App/AppContainer.js
src/components/AppNavBar/AppNavBarPresentation.js
src/components/ConditionsOfUse/ConditionsOfUsePresentation.js
src/components/Disclaimer/DisclaimerPresentation.js
src/components/LandingPage/LandingPageData.js
src/components/WidgetText/WidgetTextPresentation.js

created About FirstVoices page and added in relevant links in appNavBar and About FV widget
N/A

Fw 5334 firstvoices about page

---

src/components/Form/MediaArrayField.js
src/components/Modal/ModalPresentation.js

- Updated margin and height of media container dialog box
N/A

FW-5211 Updated styling of media container dialog box

---

src/common/constants/paths.js
src/common/utils/gameHelpers.js
src/components/Game/GamePresentation.js
src/components/Game/Wordsy/Utils/Grid.js
src/components/Game/Wordsy/Utils/Keyboard/Keyboard.js
src/components/Game/Wordsy/Utils/Rows/CurrentRow.js
src/components/Game/Wordsy/Utils/helpers.js
src/components/Game/Wordsy/WordsyContainer.js
src/components/Game/Wordsy/WordsyData.js
src/components/Game/Wordsy/WordsyPresentation.js
src/services/api/gameContent.js
src/services/api/index.js

Fw 5263 hook up wordsy with the new be

---

src/components/UserMenu/UserMenuPresentation.js

added menu item and link, styled
N/A

FW-5010-support-link-user-menu

---

src/components/Story/StoryPresentation.js

moved audio player so it is above wysiwyg paragraph in intro and pages
N/A

FW-4382-move-audio-top-story-page

---

src/components/LandingBanner/LandingBannerData.js

Uncomments the search section on the FV landing page, allowing it to direct to the FV-wide search page.
N/A

FW-5387 Re-enable search section on FV landing page

---

src/common/icons/Wordsy.js
src/common/utils/getIcon.js
src/components/Games/GamesPresentation.js

- re-enabled games page, changed `wordle` icon file to `wordsy`
N/A

FW-5408 re enable games page

---

cypress/e2e/core_suite_master.cy.js

Changed some wording, removed commented out code
N/A

FW-5471-changed text for categories

---

src/components/Games/GamesPresentation.js

This PR adds a "Games" header to the games page matching other pages.
N/A

FW-5484 Add header to games page

---

src/components/AppNavBar/AppNavBarPresentation.js

- Standardized styling of menu items in navbars
- updated mobile navbar to use internal pages
N/A

FW-5485, FW-5486 Main and Mobile Navbar fixes

---

src/components/Keyboards/Keyboards.js

FW-5371-keyboards-page-update

---

src/assets/locale/en.js
src/common/dataAdaptors/immersionAdaptors.js

- Removes the two instances where code was being fudged to accommodate old transkeys, as the BE has been updated with the correct new transkeys.
N/A

FW-5423 Remove accommodation for old immersion transkeys

---

src/components/AppNavBar/AppNavBarPresentation.js

This PR hides the search bar in the app nav when on the FV-wide search page, as having two search bars on that page is redundant.
N/A

FW-5493 Remove app nav search bar from FV-wide search page

---

src/common/utils/validationHelpers.js
src/common/utils/widgetHelpers.js
src/components/WidgetCrud/WidgetCrudPresentation.js
src/components/WidgetCrud/WidgetFormMaps.js

This PR adds a form for the WIDGET_IFRAME type (map widget), including URL validation. Additionally, the widget has been enabled.
N/A

FW-3840 Add map widget form and enable map widget

---

src/components/AppNavBar/AppNavBarPresentation.js
src/components/DashboardImmersion/DashboardImmersionPresentation.js
src/components/JoinModalButton/JoinModalButtonContainer.js
src/components/NavBar/NavBarPresentation.js
src/components/NavBar/NavBarPresentationMenu.js
src/components/NavBar/NavBarPresentationMobile.js

- Mobile site nav bar: add immersion labels 
- Site Navbar: truncate immersion labels and add tooltip to display full label on hover
- Site Navbar drop-down menus: wrap immersion labels
- Navbar optimizations for lg vs xl screens
- Remove beta and beta modal from site & app navbars
N/A

FW-5420, FW-5472 immersion labels

---

src/services/api/videoLinkThumbnails.js

Fix vimeo thumbnail API export

---

src/components/Dictionary/DictionaryData.js
src/components/Dictionary/DictionaryPresentation.js

added results total and styled to words/phrases
N/A

FW-3167-total-num-words-phrases

---

src/components/Alphabet/AlphabetPresentationSelected.js

changed styling so icons wrap and title width full
N/A

FW-4987-too-many-related-audio-related-entry-bug

---

src/components/Dictionary/DictionaryContainer.js
src/components/Dictionary/DictionaryPresentation.js

forgot to send the count through the container layer. It caused undefined reading in the presentation layer.  Oops!
N/A

Fw 3167 num words phrase revamp

---

src/components/WidgetContactUs/WidgetContactUsPresentation.js

removed Follow Us if there are no links
N/A

FW-5543-contact-widget-follow-us

---

src/common/utils/stringHelpers.js
src/components/Game/PhraseScrambler/PhraseScramblerData.js

- added utility to normalize spaces in phrases, and added that utility in phraseScrambler game to resolve issue of some words having more than one whitespace
N/A

FW-5544 fixed whitespace issue in phrasescrambler game

---

src/components/CategoriesBrowser/CategoriesBrowserPresentation.js
src/components/Keyboards/Keyboards.js
src/components/LandingPage/LandingPageData.js
src/components/Resource/ResourcePresentation.js

FW-5550 fixed typos on homepage

---

src/components/Alphabet/AlphabetPresentationSelected.js

changed styling to horizontal orientation, changed colour of related word title, bold font for alphabet widget selected character
N/A

Fw 5551 example word layout optimization

---

src/components/Alphabet/AlphabetPresentationSelected.js

made text in related content translation center aligned
N/A

Fw 5551 alphabet related revamp

---

src/components/Form/MediaArrayField.js

* enhance youtube thumbnail component to support youtu.be short urls
N/A

fw-5554, support thumbnails for youtu.be urls

---

src/components/StoryCrud/StoryCrudPreview.js
src/components/StoryPagesCrud/StoryPagesCrudPreview.js

* story page edit form preview
* story preview (final step)
N/A

fw-5380, thumbnails for linked videos on the story page preview form

---

src/components/Dictionary/DictionaryPresentation.js

FW-5557 Dictionary pages results load fix

---

src/components/Game/Parachute/ParachutePresentation.js

Fw 5560 parachute wording updates

---

src/components/NavBar/NavBarPresentation.js

Adjust size and spacing of short logo

---

src/components/Game/Parachute/ParachutePresentation.js
src/components/WidgetText/WidgetTextPresentation.js
src/components/WidgetTextConcise/WidgetTextConcisePresentation.js

fixed conditional for href to include sitename for widget buttons
N/A

FW-5545-internal-links-new-tab

---

src/common/constants/searchParams.js
src/components/Game/PhraseScrambler/PhraseScramblerData.js

- Added a minWords filter to the phraseScrambler game to prevent showing 1 word phrases.
N/A

FW-5549 PhraseScrambler min num of words filter

---

src/components/Alphabet/AlphabetPresentationSelected.js
src/components/DashboardEntries/DashboardEntriesPresentationList.js

Add missing span tags

---

src/common/dataAdaptors/audienceAdaptors.js
src/common/dataAdaptors/mediaAdaptors.js
src/common/dataHooks/useMedia.js
src/components/DashboardEdit/DashboardEditContainer.js
src/components/Form/AutocompleteMultiple.js
src/components/MediaDetails/MediaDetailsAudio.js
src/components/MediaEdit/MediaEditContainer.js
src/components/MediaEdit/MediaEditData.js
src/components/MediaEdit/MediaEditPresentation.js
src/components/MediaEdit/index.js
src/services/api/media.js

- Added and refactored relevant media adaptors.
- Added mediaUpdateApi and useMediaUpdate hook
- Added component to handle media editing, working only for `Audio` as of this PR. 
N/A

Fw 5575 edit audio form

---

src/common/dataAdaptors/mediaAdaptors.js
src/common/utils/membershipHelpers.js
src/components/DashboardEdit/DashboardEditContainer.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js
src/components/Form/Audience.js
src/components/Form/index.js
src/components/JoinModalButton/JoinModalButtonData.js
src/components/Languages/LanguagesPresentation.js
src/components/MediaDetails/MediaDetailsAudio.js
src/components/MediaDetails/MediaDetailsVisual.js
src/components/MediaEdit/MediaEditContainer.js
src/components/MediaEdit/MediaEditPresentation.js
src/components/NavBar/NavBarPresentationMobile.js
src/services/api/media.js

- Added `isAtLeastEditor` membership helper utility to be used as a filter on displaying Edit button.
- Added routes for image and video editing
- moved `acknowledgement` in mediaAdaptor to be available for all media types.
N/A

Fw 5613 edit visual media form

---

.github/workflows/build-frontend.yml

- Fixed the if-clause in build-frontend.yml
N/A

FW-5705 Dependabot action if-clause fix

---

.github/workflows/build-frontend.yml
.github/workflows/cypress-tests-dependabot.yml

Moved Cypress test for dependabot to separate workflow
N/A

FW-5705 Moved Cypress test for dependabot to separate workflow

---

src/components/MediaCrud/UploadMedia.js
src/components/MediaEdit/MediaEditPresentation.js

- Hide toggles on Video edit forms
- Remove toggles from video upload form
N/A

FW-5702 hide audience toggles on video forms

---

src/common/dataAdaptors/basicDatesAdaptor.js
src/common/dataAdaptors/index.js
src/common/dataHooks/useSearchLoader.js
src/common/utils/stringHelpers.js
src/components/DashboardEntries/DashboardEntriesPresentationList.js
src/components/DashboardJoinCard/DashboardJoinCardPresentation.js

- added concise date with time helper
- included dates in search data adaptor
- added dates column to Dashboard entry lists
N/A

FW-5691 dates in reports

---

src/common/constants/searchParams.js
src/common/utils/stringHelpers.js
src/components/AdvancedSearchOptions/AdvancedSearchOptionsPresentation.js
src/components/DashboardEntries/DashboardEntriesPresentationList.js
src/components/DashboardEntries/SortByHeader.js

Pull main back to dev

---

src/common/constants/searchParams.js
src/common/utils/stringHelpers.js
src/components/AdvancedSearchOptions/AdvancedSearchOptionsPresentation.js
src/components/DashboardEntries/DashboardEntriesPresentationList.js
src/components/DashboardEntries/SortByHeader.js

Merge Main to dev

---

src/common/utils/stringHelpers.js

Adds extra check for string with length before processing to Date
N/A

FW-5727 Add check for string with length before procssing date

---

.github/workflows/cypress-tests-dependabot.yml
.github/workflows/sonarcloud.yml
cypress.config.js
package.json

- Added cypress test suite workflow for dependabot PRs
- Enabled sonarcloud workflow for branches on dev
N/A

FW-5705 Adding Cypress tests to dependabot PRs

---

.github/workflows/cypress-tests-dependabot.yml

- Removed `record` flag from cypress test suite for dependabot
N/A

FW-5705 dependabot cypress test suite fix

---

src/common/dataAdaptors/songAdaptors.js
src/common/dataAdaptors/storyAdaptors.js
src/components/DictionaryList/DictionaryListPresentation.js

- updated song and story dataAdaptors to not add translations array
- added titleTranslation in DictionaryListPresentation
N/A

FW-5763 Fixed inconsistent translations for songs and stories

---

src/components/LandingBanner/LandingBannerPresentation.js

added background colour to banner
N/A

Fw 5571 background colours landing page

---

src/common/hooks/useEditForm.js
src/components/DictionaryCrud/DictionaryCrudData.js

Added useMemo to prevent re-rendering of forms

---

src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/DictionaryList/DictionaryListPresentation.js

added other spellings array to word drawer and detail views. 
added key values so react isn't cranky
N/A

Fw 5668 display alt spelling dictionary

---

src/components/DashboardEdit/DashboardEditContainer.js

Make FE route access match BE media edit access - i.e. give media edit access to Editors
N/A

FW-5864 Give media edit access to Editors

---

package-lock.json
package.json
src/index.js

Updated ReactRouterIntegration with sentry/react 8.x

---

src/components/DictionaryCrud/DictionaryCrudPresentation.js

increased allowed notes to 10 for dictionary entries
N/A

FW-6030-increase-notes-dictionary-entries

---

src/common/utils/validationHelpers.js
src/components/StoryPagesCrud/StoryPageForm.js
src/components/WidgetCrud/WidgetFormText.js
src/components/WidgetCrud/WidgetFormTextFull.js
src/components/WidgetCrud/WidgetFormTextIcons.js

Add custom validation definition for required wysiwyg fields
N/A

FW-5109 validation definition for required wysiwyg fields

---

src/components/ErrorHandler/ErrorHandlerContainer.js
src/components/WidgetQuotes/WidgetQuotesPresentation.js

changed styling so that it stayed within the confines of the quotes bubble at tablet size
N/A

Fw 5548 quotes widget ipad mobile

---

cypress/e2e/dashboard/stories.cy.js
cypress/e2e/navigation.cy.js

FW-5738-fixes navigation and stories tests

---

src/components/Game/PhraseScrambler/PhraseScramblerPresentation.js

Fw 5405 games phrase scrambler words placement

---

src/components/SongCrud/SongCrudData.js

updated useNavigate so it functions
N/A

Fw 5962 edit song cancel btn

---

src/components/Footer/FooterPresentation.js

fixed alignment issues with phone number
N/A

FW-4714-footer-data-alignment

---

src/components/Alphabet/AlphabetPresentationSelected.js
src/components/DashboardCreate/DashboardCreateContainer.js
src/components/DashboardCreate/DashboardCreateData.js
src/components/DashboardEdit/DashboardEditContainer.js
src/components/DashboardEdit/DashboardEditData.js
src/components/MediaDetails/MediaDetailsAudio.js
src/components/MediaDetails/MediaDetailsVisual.js

- route access to edit media and galleries
- add tiles for create and edit galleries on respective landing pages
- expose edit button on media detail panel
N/A

FW-4833 assistants edit media

---

src/components/MediaBrowser/MediaBrowserData.js
src/components/MediaCrud/MediaCrudData.js

FW-5731-media-dashboards-sort

---

src/components/MediaCrud/UploadMedia.js

FW-5703 Refactored UploadMedia to remove useUppy hook

---

.prettierrc.js
src/components/App/AppContainer.js
src/components/App/LegacyRedirect.js

Added redirection for legacy urls - type and specific entries
N/A

FW-5917 forward v1 entry urls

---

src/components/Story/StoryPresentation.js

display story page notes to public facing side
N/A

FW-4933-display-story-page-notes

---

src/components/Game/PhraseScrambler/PhraseScramblerPresentation.js

FW-6081-word-scrambler-guessed-words-mobile

---

src/components/CharacterCrud/CharacterCrudPresentation.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js
src/components/Form/AudioArrayField.js
src/components/Form/AudioIdField.js
src/components/Form/Autocomplete.js
src/components/Form/AutocompleteMultiple.js
src/components/Form/CategoryArrayField.js
src/components/Form/EntryArrayField.js
src/components/Form/FieldLabel.js
src/components/Form/FileUploadField.js
src/components/Form/GalleryField.js
src/components/Form/HelpText.js
src/components/Form/ImageArrayField.js
src/components/Form/ImageIdField.js
src/components/Form/RadioButtons.js
src/components/Form/Select.js
src/components/Form/SelectOneMedia.js
src/components/Form/TextAreaField.js
src/components/Form/TextArrayField.js
src/components/Form/TextField.js
src/components/Form/TextTranslationArrayField.js
src/components/Form/VideoArrayField.js
src/components/Form/WysiwygField.js
src/components/Form/index.js

- Reusable form components for FieldLabels and HelpText
- Expand use of ValidationError
N/A

Reusable form components for FieldLabels and HelpText

---

src/components/Home/HomePresentation.js
src/components/WidgetApps/WidgetAppsPresentation.js

Fixed styling so that logo displays when there is no homepage banner or video selected
N/A

FW-6108 no banner results in no logo

---

src/components/Game/PhraseScrambler/PhraseScramblerPresentation.js

Fw 6081 word scrambler guessed words mobile

---

src/common/constants/paths.js
src/common/dataHooks/useMedia.js
src/common/dataHooks/useMediaSearch.js
src/components/MediaEdit/MediaEditData.js

Fix for media edit redirects
N/A

FW-6124 after editing an image screen goes blank

---

src/common/dataHooks/useMediaSearch.js
src/components/DashboardMediaAudio/DashboardMediaAudioContainer.js
src/components/DashboardMediaVisual/DashboardMediaVisualContainer.js
src/components/SearchSelector/SearchSelectorPresentation.js

Fix bug where navigation was being executed on media modal. 
Only update url searchParams on Dashboard media pages
N/A

FW-6127 Only update url searchParams on Dashboard media pages

---

src/components/VisualMediaSelector/VisualMediaSelectorContainer.js

Update placeholder text for VisualMediaSelector
N/A

FW-6129 Update placeholder text for VisualMediaSelector

---

package-lock.json
src/components/LandingBanner/LandingBannerPresentation.js

added conditional for minimum screen hight to banner  title
N/A

FW-5039-landing-page-image-overlap

---

src/components/AddMediaModalWrapper/AddMediaModalWrapper.js
src/components/UploadAudio/UploadAudio.js
src/components/UploadVisualMedia/UploadVisualMedia.js

FW-6135 Adjust scrolling for AddMediaModal

---

src/components/ImageWithLightbox/ImageWithLightboxPresentation.js

fixed css issue with images having grey space at the bottom
N/A

FW-5924-long-image-layout-description-acknowledgement

---

src/components/WidgetKeyboards/WidgetKeyboardsPresentation.js

adjusted css for better visibility
N/A

FW-6015-keyboard-widget-css

---

src/components/SiteApps/SiteAppsPresentation.js
src/components/WidgetApps/WidgetAppsPresentation.js

FW-6128 update siteapps page

---

src/components/Footer/FooterPresentation.js

FW-6158-update-donate-link

---

src/components/AddImageModal/AddImageModalContainer.js
src/components/Form/ImageArrayField.js
src/components/Form/ImageIdField.js
src/components/HomeCrud/HomeForm.js
src/components/SelectorImages/SelectorImagesContainer.js

Allow for hiding shared media on logo selector and widget image selector
N/A

FW-6181 Hide shared media on logo selector and widget image selector

---

.github/workflows/cypress-tests_preprod.yml

FW-6191 cypress preprod GitHub actions setup

---

cypress/e2e/dashboard/category.cy.js
cypress/e2e/dashboard/galleries.cy.js
cypress/e2e/dashboard/media.cy.js
cypress/e2e/dashboard/pages.cy.js
cypress/e2e/dashboard/phrases.cy.js
cypress/e2e/dashboard/reports.cy.js
cypress/e2e/dashboard/songs.cy.js
cypress/e2e/dashboard/speaker.cy.js
cypress/e2e/dashboard/stories.cy.js
cypress/e2e/dashboard/wordup.cy.js
cypress/e2e/login/immersion.cy.js
cypress/e2e/search.cy.js

FW-5734-fixes existing tests to latest code

---

public/index.html

- Added missing env variable for APP_ENV
N/A

FW-6094 added APP_ENV variable for caddy config

---

src/components/KidsNavBar/KidsNavBarPresentation.js

FW-6228 Restore logo to kids nav

---

src/components/DashboardEdit/DashboardEditData.js

updated wording for alphabet and immersion tiles
- [ x] PR title / commit messages contain Jira ticket number if applicable
- [x ] Review the changes here
N/A

FW-5372-inconsistent-wording-on-edit

---

src/components/AdvancedSearchOptions/SingleSelect.js
src/components/RadioButtonGroup/RadioButtonGroupPresentation.js

FW-6249 missed fv-charcoal replacements

---

src/components/DashboardSpeakers/DashboardSpeakersPresentation.js

added testid to edit speakers button
N/A

FW-6245-edit-speaker-link

---

src/common/dataHooks/useSites.js
src/components/FVApps/FVAppsData.js
src/services/api/sites.js

- Adds a pageSite parameter and defaults to useSites, allowing the page size to be manually set
- Sets page size to 250 for the apps page sites fetch
N/A

FW-6216 Add pagesize to useSites to allow for more apps on apps page

---

src/components/App/AppContainer.js
src/components/SelectorVisualMediaGrid/SelectorVisualMediaGridPresentation.js
src/components/SiteApps/SiteAppsPresentation.js
src/components/WidgetApps/WidgetAppsPresentation.js

- updated colour for site pp page to be consistent
- added redirect for `/en` routes
- use media path helper in media selector grid component
N/A

FW-6231, FW-6229, FW-6230 font colour, app route redirect, fallback to original image

---

src/components/FVApps/FVAppsPresentation.js

optimized apps page for mobile and readjusted for tablet and installation instructions updated
N/A

FW-6234-apps-list-optimization-mobile-update-instructions

---

src/components/Audiobar/AudiobarPresentation.js
src/components/SelectorAudio/SelectorAudioPresentation.js

fixes to make media library songs whole area clickable and changing the colour of the audio bar x buton on hover 
N/A

Fw 5398 5395 5397 various css fixes

---

cypress/e2e/dashboard/category.cy.js
cypress/e2e/dashboard/speaker.cy.js
cypress/e2e/login/login.cy.js
cypress/e2e/word.cy.js

FW-5922-fixes tests to latest code

---

src/components/Song/SongData.js
src/components/Story/StoryData.js

added error handling to songs and story data
N/A

FW-5654-stories-detail-page-infinitely-loads-members-only

---

package-lock.json
package.json
webpack/webpack.common.js
webpack/webpack.production.js

- Added uglify JS plugin
- split CSS into a separate chunk
- Added CSS minimizer
N/A

FW-6217 Minify JS on prod

---

package-lock.json
package.json

Update to @bcgov/bc-sans 2.1.0
N/A

Update to latest bcsans

---

package-lock.json
package.json

Reverts First-Peoples-Cultural-Council/fv-web#690

Revert "Bump react-router-dom from 6.28.0 to 7.0.1"

---

package-lock.json
package.json
webpack/webpack.common.js

Revert "FW-6217 Minify JS on prod"

---

src/components/Gallery/GalleryPresentation.js

added titles to photo project gallery
N/A

FW-6296-display-image-titles-gallery

---

src/components/DashboardEntries/DashboardEntriesPresentationList.js
src/components/Gallery/GalleryPresentation.js
src/components/ImageWithLightbox/ImageWithLightboxPresentation.js

- restore mosaic columns to gallery view
- restore color to types in DashboardEntries list
N/A

FW-6296 restore mosaic

---

package-lock.json
package.json

Reverts First-Peoples-Cultural-Council/fv-web#702

Revert "Bump i18next from 23.16.8 to 24.0.2"

---

src/components/ErrorHandler/ErrorHandlerData.js

Ensure the back button defaults to Landing page on `site` error responses
N/A

FW-6330 Ensure the back button defaults to Landing page if no site

---

src/common/hooks/useGoBack.js
src/components/ErrorHandler/ErrorHandlerData.js

Reverts ErrorHandler to use standard browser back behaviour for "Go back"
N/A

FW-6330 restore browserlike go back behaviour

---

src/common/dataAdaptors/basicDatesAdaptor.js
src/common/dataAdaptors/songAdaptors.js
src/components/EntryDetail/EntryDetailContainer.js
src/components/Song/SongContainer.js
src/components/Song/SongPresentationDrawer.js

added created and modified conditionally to dashboard side for songs
N/A

FW-6310-add-created-modified-songs

---

src/common/dataAdaptors/storyAdaptors.js
src/components/EntryDetail/EntryDetailContainer.js
src/components/Song/SongPresentationDrawer.js
src/components/Story/StoryContainer.js
src/components/Story/StoryPresentationDrawer.js

added created and modified to stories with boolean so it only shows on Dashboard
N/A

Fw 6311 add created modified stories

---

cypress/e2e/dashboard/category.cy.js
cypress/e2e/dashboard/speaker.cy.js

adds in edit speaker and edit category
N/A

FW-5922-fixes edit speaker and a few other things

---

src/common/dataHooks/useGamesSearch.js
src/components/AddMediaModalWrapper/AddMediaModalWrapper.js
src/components/Game/Parachute/ParachuteContainer.js
src/components/Game/Parachute/ParachuteData.js
src/components/Game/Parachute/ParachutePresentation.js

- Restored scrollbar to add audio modal
- Fixed infinite loading on "Pull Together" which was causing correctly guessed characters to disappear
N/A

FW-6359, FW-6362 upload audio missing upload file button and Pull Together bug

---

.github/workflows/cypress-tests-dependabot.yml
.github/workflows/cypress-tests_preprod.yml

- Added `CYPRESS_DIALECT` env variable for dependabot and preprod test suite
N/A

Cypress dialect fix for dependabot and preprod tests

---

.github/workflows/cypress-tests-dependabot.yml

- Added record flag to cypress dependabot suite
N/A

Added record flag to cypress dependabot suite

---

src/components/SelectorImages/SelectorImagesContainer.js

changed text and added link to KB artists page
N/A

FW-6332-update-media-selector-text

---

src/components/SelectorImages/SelectorImagesContainer.js

FW-6332-update-image-tab

---

.github/workflows/cypress-tests-dependabot.yml
cypress.config.js

- Added projectId to cypress.config.js
N/A

Cypress user_suite dependabot bug fix

---

.github/workflows/cypress-tests-dependabot.yml

- Hardcoded CYPRESS_DIALECT since dependabot PRs cannot access GH secrets
N/A

Add value of CYPRESS_DIALECT direclty to cypress-tests.dependabots.yml file

---

src/common/dataHooks/useCreateUppy.js
src/common/dataHooks/useMedia.js
src/common/utils/mediaHelpers.js
src/components/DashboardMediaDetails/DashboardMediaDetailsPresentation.js
src/components/ImgFromId/ImgFromIdContainer.js
src/components/MediaEdit/MediaEditContainer.js
src/components/MediaEdit/MediaEditData.js
src/components/MediaEdit/MediaEditPresentation.js
src/components/MediaThumbnail/AudioThumbnail.js
src/components/MediaThumbnail/ImageThumbnail.js
src/components/MediaThumbnail/VideoThumbnail.js
src/components/SpeakerCrud/SpeakerCrudPresentation.js
src/components/WidgetCrud/WidgetFormText.js
src/components/WidgetQuotes/WidgetQuotesPresentation.js
src/components/WidgetText/WidgetTextPresentation.js
src/components/WidgetTextConcise/WidgetTextConcisePresentation.js
src/services/api/media.js

- Addresses missing `documents` api config in useMedia
- consolidates and standardizes media data hooks and api service
- Bonus FW-6354 fixes form for Text widget to allow setting coloured background
- Bonus - increase char limit for speaker bio in FE and change to text area
N/A

FW-6456, FW-6354 document editing dashboard

---

src/common/constants/media.js

Adds the 'oga', 'opus' and 'weba' extensions to SUPPORTED_AUDIO_EXTENSIONS
N/A

FW-6477 Add opus, oga and weba support to FE uploads

---

src/common/dataHooks/useAudio.js

- corrects the return value of `createJoinRequest` in `useAudio.js`
N/A

FW-6526 Fix audio uploads

---

package-lock.json
package.json
webpack/webpack.common.js

- Upgrade webpack and webpack-dev-server
- uninstall clean-webpack-plugin
- Switch to built-in webpack output clean
N/A

FW-6537 Upgrade webpack and uninstall clean-webpack-plugin

---

src/components/WidgetImage/WidgetImagePresentation.js

FW-3618-image-widget-padding

---

src/common/dataHooks/useCharacters.js
src/components/Alphabet/AlphabetPresentation.js
src/components/Alphabet/AlphabetPresentationSelected.js
src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/RelatedDocumentsList/RelatedDocumentsListPresentation.js
src/components/Song/SongPresentation.js

- Adds a `RelatedDocumentsList` to `AlphabetPresentationSelected` to display the one related document.
- Adds relatedDocuments to useCharacters
- ESLint fixes
N/A

FW-6455 Add related document display to characters

---

src/components/Game/PhraseScrambler/PhraseScramblerPresentation.js

FW-6434-phrase-scrambler-btn

---

src/common/utils/mediaHelpers.js

adjusted getReadableFileSize to be conditional for small files to display in kb
N/A

FW-5105-audiobar-show-file-size-in-KB-instead-MB

---

src/components/WidgetVideo/WidgetVideoPresentation.js

removed autoplay mute and added controls to video
N/A

FW-6507-video-widget-controls

---

src/common/hooks/useArrayStateManager.js
src/components/SearchAllSites/SearchSitesFilter.js

- Replaces `onLanguageSelect` with `handleSiteToggle` and `handleLanguageToggle`
- adds remove`AllItemsFromArray` to `useArrayStateManager` for removal of a set of items
N/A

FW-6525 handle unselect toggles in SearchSitesFilter

---

src/components/DashboardMediaDetails/DashboardMediaDetailsPresentation.js

added ids to the bottom of the details list
N/A

FW-6532-add-ids-detail-view-individual-media-items

---

src/components/DashboardMediaDetails/DashboardMediaDetailsPresentation.js
src/components/DashboardMediaVisual/DashboardMediaVisualPresentation.js

added copy button to ID for media details
N/A

Fw 6533 add copy id btn media details

---

src/components/Alphabet/AlphabetPresentationSelected.js
src/components/DashboardReports/DashboardReportsData.js
src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/RelatedDocumentsList/RelatedDocumentsListPresentation.js
src/components/Story/StoryPresentation.js

- Categories Report title change
- Related documents styling adjustments to match designs
N/A

Categories Report title change and Related documents styling adjustments

---

src/common/dataHooks/useLanguages.js
src/components/Languages/LanguagesData.js
src/services/api/languages.js

- add the new explorable param for the languages api, and use it on the Explore Languages page
N/A

fw-6602, add explorable param for languages api

---

src/components/Game/Parachute/ParachutePresentation.js

made set height start at medium width so that image is not too wide at mobile width
N/A

FW-6502-pull-together-mobile-image

---

src/components/About/About.js

changed wording on About Us

---

src/components/Form/GalleryField.js

adjusted css to scroll galleries on widgets
N/A

FW-6494-gallery-goes-beyond-container

---

.github/pull_request_template.md

updated template to include ui review
N/A

FW-6633-Add-ui-review-fv-web-pr-template

---

src/components/WidgetKeyboards/WidgetKeyboardsPresentation.js

added conditional statement for desktop urls
N/A

FW-6605-hide-desktop-keyboard-label-keyboards-widget-when-desktop-url-blank

---

src/components/Story/StoryPresentation.js

related conditional expanded to check for related documents
N/A

FW-6609 - displays related document

---

src/components/WidgetKeyboards/WidgetKeyboardsPresentation.js

refactored as it failed QA
N/A

Fw 6605 hide desktop keyboard label keyboards widget when desktop url blank again

---

src/components/CategoriesBrowser/CategoriesBrowserPresentation.js
src/components/DeleteButton/DeleteButtonPresentation.js
src/components/VideoLinkForm/VideoLinkForm.js

missed a few btns in the dashboard. Found in QA
N/A

Fw 6626 convert remaining dashboard btns missed one

---

src/components/DictionaryGrid/DictionaryGridPresentation.js
src/components/DictionaryGridTile/DictionaryGridTilePresentationKids.js

made responsive so long words visible in mobile and tablet
N/A

FW-6503-mobile-phone-kids-dictionary-cannot-see-full-word

---

src/components/Support/Support.js

updated buttons, made responsive for mobile, corrected spacing
N/A

Fw 6629 UI upgrades support page

---

src/components/CategoriesBrowser/CategoriesBrowserContainer.js
src/components/CategoriesBrowser/CategoriesBrowserPresentation.js

Added multiselect to categories
Added checkmark upon selecting like dictionary
Added few things due to lint

FW-6304 - Added multiselect or categories

---

src/components/DictionaryDetail/DictionaryDetailPresentationKids.js

adjusted layout for individual kids words dictionary
N/A

FW-6503-mobile-kids-dictionary-layout

---

src/components/DashboardImmersion/ImmersionCrudForm.js
src/components/Form/EntryArrayField.js
src/components/SelectorEntries/SelectorEntriesContainer.js

Limits immersion label to only one entry
N/A

FW-6599 immersion labels single entry

---

src/components/Maintenance/Maintenance.js

Added debug statement for under maintenance flag

---

README.md

Dummy commit to toggle the maintenance flag

---

src/components/DashboardCreate/DashboardCreateContainer.js
src/components/DashboardEdit/DashboardEditContainer.js

Remove maintenance wrapper from widgets, songs , and stories
N/A

Remove maintenance wrapper

---

README.md

Dummy commit to trigger server rebuild

---

src/components/SearchSiteForm/SearchSiteFormContainer.js

FW-6617 - Added clear button

---

package-lock.json
package.json
src/index.js

- Upgrade to @sentry/react 9.41.0
- Fix out of sync BrowserTracingIntegration
N/A

FW-6725 upgrade sentry react to v9

---

src/components/ByAlphabet/ByAlphabetPresentation.js

adjusted grid to see end of row in tablet mode
N/A

FW-5128-ipad-cant-see-three-dots-or-copy-option

---

src/components/DictionaryGridTile/DictionaryGridTilePresentation.js

Removed conditional that caused inconsistent font sizes and went with the smaller option of the conditional 
N/A

FW-5928 - Inconsistent font sizes

---

src/components/AddAudioModal/AddAudioModalContainer.js
src/components/AddDocumentModal/AddDocumentModalContainer.js
src/components/AddImageModal/AddImageModalContainer.js
src/components/AddMediaModalWrapper/AddMediaModalWrapper.js
src/components/AddVideoModal/AddVideoModalContainer.js
src/components/MobileApps/MobileAppsPresentation.js
src/components/SelectorEntries/SelectorEntriesContainer.js
src/components/SelectorImages/SelectorImagesContainer.js
src/components/Support/Support.js

- Make casing in add media modals more consistent
- Update copy on "Support" and "Apps" pages
N/A

FW-6611, FW-6730 image modal casing, and copy update

---

src/components/AudioCrud/AudioBaseForm.js
src/components/Form/AutocompleteMultiple.js

Use separate state control for combobox
N/A

FW-6724 speaker select part 3

---

src/components/Join/JoinForm.js

Added - Max height of max-h-72. which is 18 rem i believe
Added - overflow-auto in the odd case someone needs to write a monologue to join a website.
N/A

FW-5185 - Added max height to join request

---

src/components/PageCrud/PageForm.js
src/components/WidgetCrud/WidgetFormBase.js

Fixes issue where the visibility select is cut off at the bottom of Widget forms and Custom Page form
N/A

FW-6739 visibility select cutoff

---

src/components/DashboardFooter/DashboardFooterPresentation.js
src/components/MembershipCrud/MembershipCrud.js

- add cursor pointer to radio buttons and expand clickable area to include labels
- Center Dashboard footer
N/A

FW-6679 membership tweaks

---

src/components/WidgetText/WidgetTextPresentation.js

Prior changes only worked.
new fix
N/A

FW-5628 QA fix

---

src/components/CategoryCrud/CategoryCrudContainer.js
src/components/CharacterCrud/CharacterCrudContainer.js
src/components/Dashboard/DashboardContainer.js
src/components/DashboardCreate/DashboardCreateContainer.js
src/components/DashboardEdit/DashboardEditContainer.js
src/components/DashboardEntries/DashboardEntriesPresentation.js
src/components/DashboardLanding/DashboardLandingPresentation.js
src/components/DashboardMedia/DashboardMediaContainer.js
src/components/DashboardMediaAudio/DashboardMediaAudioPresentation.js
src/components/DashboardMediaDocuments/DashboardMediaDocumentsPresentation.js
src/components/DashboardMediaVisual/DashboardMediaVisualContainer.js
src/components/DashboardReports/DashboardReportsContainer.js
src/components/DictionaryCrud/DictionaryCrudContainer.js
src/components/GalleryCrud/GalleryCrudPresentation.js
src/components/HomeCrud/HomeCrudPresentation.js
src/components/PageCrud/PageCrudContainer.js
src/components/SongCrud/SongCrudContainer.js
src/components/SpeakerCrud/SpeakerCrudContainer.js
src/components/StoryCoverCrud/StoryCoverCrudContainer.js
src/components/StoryCrud/StoryCrudContainer.js
src/components/WidgetCrud/WidgetCrudContainer.js

FW-6316 - Dochead title added

---

src/components/WidgetAreaEdit/WidgetAreaEditData.js

Prevent infinite loading of widgets
