src/common/dataAdaptors/mediaAdaptors.js
src/common/utils/mediaHelpers.js
src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/DictionaryDetail/DictionaryDetailPresentationKids.js
src/components/Gallery/GalleryPresentationWidget.js
src/components/ImageWithLightbox/ImageWithLightboxPresentation.js
src/components/LazyImage/LazyImage.js
src/components/MediaBrowser/MediaBrowserData.js
src/components/MediaItemsLayout/MediaItemsLayoutAudio.js
src/components/MediaItemsLayout/MediaItemsLayoutVisual.js
src/components/MediaThumbnail/ImageThumbnail.js
src/components/Song/SongPresentation.js
src/components/Story/StoryPresentation.js

- Fix image styling on ImageWithLightbox
- Remove mouse click pointer from Hompage banner
- Increase size of info icon on ImageWithLightbox and videos on DictionaryDetail
- Add backup original path to getMediaPath when thumbnails are null
- Move mediaDataAdaptor into dataAdaptors folder and rename
N/A

FW-4727, FW-4718, FW-4710 fix broken images

---

src/common/utils/authHelpers.js
src/components/App/AppData.js
src/context/UserContext.js
src/index.js
src/services/api/categories.js
src/services/api/characters.js
src/services/api/dictionary.js
src/services/api/media.js
src/services/api/pages.js
src/services/api/partsOfSpeech.js
src/services/api/people.js
src/services/api/search.js
src/services/api/site.js
src/services/api/song.js
src/services/api/stories.js
src/services/api/widgets.js
src/services/config.js

- Token were already being refreshed, but the auth headers were never updated to use the new tokens. This changes apiBase to a function that always gets the latest token for the auth headers. (Performance is surprisingly fine!)
- Added handling for expired tokens-- instead of using them, we ignore them and treat the user as logged out.
N/A

Fw-4637, auto-refresh auth tokens

---

src/common/dataHooks/useSearchLoader.js
src/components/CategoryCrud/CategoryCrudData.js
src/components/DictionaryCrud/DictionaryCrudData.js
src/services/api/search.js

- fixed bug where search infinite scroll was loading the same page over and over
- Allow assign parent category on category create
- Ensure dictionary crud cancel button always exits form - will now return to 'dashboard/create'
N/A

FW-4778, FW-4797, FW-4791 lazy loading only loads first page

---

src/components/Dashboard/DashboardPresentationSiteSelect.js
src/components/DashboardLocator/DashboardLocatorPresentation.js
src/components/Home/HomePresentation.js

* homepage banner is always a circle (height and width on same element)
* 2 dashboard logos and 3 homepage logo options all have same cropping style
* also i logged a ticket to make one reusable logo to rule them all (fw-4846)
N/A

fw-4826, all logos have same cropping

---

src/common/dataHooks/usePages.js
src/common/dataHooks/useSites.js
src/components/WidgetAreaEdit/WidgetAreaEditData.js

- Fixed bug where widgets couldn't be added to a homepage that had no widgets
- prevented refresh after reordering or adding a widget to a page
- ensured data for all widgets was available to display, not just data for the widgets already on the page.
N/A

FW-4847 can t add widget to homepage

---

src/components/WidgetCrud/WidgetFormContact.js
src/components/WidgetCrud/WidgetFormText.js
src/components/WidgetCrud/WidgetFormTextFull.js
src/components/WidgetCrud/WidgetFormTextIcons.js

* Fixes error message when creating new widgets with blank wysiwyg text fields. Validator expects a json state, so the empty value needs to be null not a blank string
N/A

fw-4830, text field validation

---

src/components/Song/SongPresentation.js
src/components/Story/StoryPresentation.js

* fix SongPresentation to match the introductionDataAdaptor field names
* Also fix 0 showing on songs and stories when data items are empty
N/A

fw-4851, fix song intros

---

src/common/constants/misc.js
src/common/dataHooks/useMutationWithNotification.js
src/common/utils/stringHelpers.js
src/common/utils/validationHelpers.js

- ensure error messages from server are included in notifications - ensures user feedback for case where an attempt is made to create a page with a duplicate slug
- Add validation message to textArray fields to prevent blank text value from being sent to server - e.g. Dictionary entry translation
N/A

FW-4821, FW-4862 duplicate page error and empty text error

---

src/common/constants/paths.js
src/common/constants/searchParams.js
src/components/Alphabet/AlphabetData.js
src/components/Alphabet/AlphabetPresentationSelected.js
src/components/ByAlphabet/ByAlphabetData.js
src/components/ByAlphabet/ByAlphabetPresentation.js
src/components/DashboardAlphabet/DashboardAlphabetPresentation.js
src/components/Site/SiteFrame.js
src/components/Site/SiteFrameKids.js

Updated the `alphabet/:character` route to `alphabet/startsWith?char={character}` to fix case where character was `.` and was ignored by router
N/A

FW-4925 Pass character in searchParams not route

---

src/components/Audiobar/AudiobarData.js
src/components/Audiobar/AudiobarPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/DictionaryList/DictionaryListPresentation.js
src/components/RelatedEntriesTable/RelatedEntriesTablePresentation.js
src/components/RelatedEntriesTable/index.js

- Fixed audio icon alignment for dictionary list view and related entries on dictionary detail - placed audio in separate column on the tables
- Matched audio icon in drawer and detail views
- Added a temporary fix for FW-2962 placed audiobar behind drawer so that the drawer isn't blocked by it
N/A

FW-2962, FW-4719 audio icon alignment

---

src/components/DictionaryGridTile/DictionaryGridTilePresentationKids.js
src/components/Drawer/DrawerPresentation.js

formatting for audio button kids words
corrected scroll behaviour on touch screen - not sure how to test this.  Will need to check with Chris as I don't have an ipad
N/A

Fw 4765 kids sound icons align

---

src/components/Alphabet/AlphabetPresentationSelected.js

changed link path so that it points to only words rather than both words and phrases
N/A

FW-4722-alphabet-btn-words-direct

---

src/common/constants/paths.js
src/common/dataAdaptors/contactUsAdaptor.js
src/common/dataHooks/useContactUs.js
src/common/utils/widgetHelpers.js
src/components/Widget/WidgetPresentation.js
src/components/WidgetAreaEdit/WidgetAreaEditPresentationSettingsPane.js
src/components/WidgetContactUs/WidgetContactUsContainer.js
src/components/WidgetContactUs/WidgetContactUsData.js
src/components/WidgetContactUs/WidgetContactUsPresentation.js
src/components/WidgetCrud/WidgetFormContact.js
src/services/api/mail.js

This PR re-enables the contact-us widget and form using the new contact-us API. 
If the user is not logged in the form fields will be hidden and text prompting the user to log in will be shown.
The edit/create widget pages will now show the list of addresses that the contact form will send emails to, as well as some text informing the user to contact support if they would like to update the list.
N/A

FW-5023 Use new contact-us API

---

src/components/StoryCrud/StoryCrudPreview.js

This PR fixes the story preview text translation being shown by default and the regular text is shown when the translation button is pressed.
N/A

FW-5100 Fix story preview text translation swap

---

src/components/DashboardTiles/DashboardTilesPresentation.js

* dynamic column styles were not being deployed for specific sizes (by tailwind); fixed by removing unused size qualifier
N/A

fw-5045, fix dashboard tiling

---

src/components/LazyImage/LazyImage.js

Lazy image was returning MEDIUM when ORIGINAL was needed
N/A

Fix size logic in LazyImage

---

src/common/utils/stringHelpers.js
src/common/utils/validationHelpers.js
src/components/Form/TextArrayField.js

* Due to a recent change, the text array field was trying to stringify a huge error object instead of just an error message. Fixed it to show the same error message it used to.
N/A

fw-5107, fix error messages for text array field

---

src/components/AppNavBar/AppNavBarPresentation.js
src/components/NavBar/NavBarPresentation.js

added missing https:// as well as added button to other navbar
N/A

FW-3856-beta-sign

---

src/common/dataAdaptors/siteAdaptors.js

reversed the order of the visibility selectors to drill down from public>members>team
N/A

FW-5074-reverse-visibility-selector

---

src/components/DashboardJoinCard/DashboardJoinCardPresentation.js

This change fixes the bug with join request approval as language admin. Note that this is a temporary fix and the permanent fix will be added in FW-5218 when the constants and display values are separated.
N/A

FW-5212 Add fix for join request approval as language admin

---

package-lock.json
package.json
src/common/constants/paths.js
src/common/dataHooks/useStats.js
src/common/utils/widgetHelpers.js
src/components/Widget/WidgetPresentation.js
src/components/WidgetStats/WidgetStatsData.js
src/services/api/index.js
src/services/api/stats.js

This PR re-enables the stats widget and connect it to the new stats API in the Django BE.
N/A

FW-4520 Use Stats API

---

src/common/dataHooks/useDictionaryEntry.js
src/common/dataHooks/useSongs.js
src/components/Form/NextPrevious.js

This PR updates the page redirects after an assistant successfully creates a word/phrase/song/story to the dashboard create page. This is a temporary fix until the dashboard edit page is updated to allow assistants access in FW-4828.
N/A

FW-4810 Update assistant page redirects after item creation

---

src/common/dataAdaptors/siteAdaptors.js
src/common/hooks/useEditForm.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js
src/components/Form/Visibility.js
src/components/PageCrud/PageForm.js
src/components/SongCrud/SongCrudPresentation.js
src/components/StoryAudienceCrud/StoryAudienceCrudPresentation.js
src/components/WidgetCrud/WidgetFormApps.js
src/components/WidgetCrud/WidgetFormBase.js
src/components/WidgetCrud/WidgetFormContact.js
src/components/WidgetCrud/WidgetFormDefault.js
src/components/WidgetCrud/WidgetFormGallery.js
src/components/WidgetCrud/WidgetFormKeyboards.js
src/components/WidgetCrud/WidgetFormLogo.js
src/components/WidgetCrud/WidgetFormQuotes.js
src/components/WidgetCrud/WidgetFormText.js
src/components/WidgetCrud/WidgetFormTextConcise.js
src/components/WidgetCrud/WidgetFormTextFull.js
src/components/WidgetCrud/WidgetFormTextIcons.js

* this fixes a sneaky bug where the visibility selector would show the correct default visibility, but it wasn't actually selected, so by default the form would always submit "public" as the value
* now the visibility selector chooses the highest (first) available visibility option and resets the form field to use that as a default
* fixed for: dictionary entries, songs, stories, pages, and all widgets
N/A

Fw-4809, set correct default visibility

---

package-lock.json
src/components/WidgetText/WidgetTextPresentation.js

- Updates the TextWithImage widget to set the background image to '' instead of undefined when no background image is selected. This avoids a failed network call to "undefined"
N/A

fw-3951, prevent undefined background image

---

src/common/utils/urlHelpers.js
src/components/App/AppContainer.js
src/components/DictionaryGridTile/DictionaryGridTilePresentationKids.js

- removed AppWrapper from Sentry.ErrorBoundary fallback - it uses Audiobar and therefore needs to be rendered inside AudiobarProvider
- Add optional chaining to all property references in entry on DictionaryGridTile - Kids
- Check for type string first in `makePlural` helper
N/A

Empty entry safeguards

---

src/components/Game/Wordsy/Utils/Keyboard/Keyboard.js

Fixed the getStatuses method to return correct status to display appropriate key color.
N/A

FW-5262 bug fix for wordsy key color after incorrect response

---

src/common/dataHooks/useGamesSearch.js
src/components/Game/GamePresentation.js
src/components/Game/Parachute/ParachuteContainer.js
src/components/Game/Parachute/ParachuteData.js

This PR adds the kids parameter to the search request in the parachute game when the parent GamePresentation component passes the prop.
N/A

FW-5214 Add kids flag to parachute

---

src/common/dataHooks/useGamesSearch.js
src/components/Game/Parachute/ParachuteData.js

Fixes a minor bug which would occur when a site dictionary hasn't been recalculated. Also removes infinite loading display when a site has valid words but no characters.
N/A

FW-5214 Fix parachute error when site doesn't have a usable dictionary

---

src/components/DashboardReports/DashboardReportsData.js

This PR updates the reports build your own page to default to both words and phrases instead of just words.
N/A

FW-5342 Set reports build your own to default to both

---

src/components/DictionaryCrud/DictionaryCrudPresentation.js

This PR adds the "include in games" option to the dictionary dashboard create and edit forms.
Note that the API was already hooked up and the toggle just needed to be re-added in the forms.
N/A

FW-5409 Add include in games toggle to dictionary dashboard forms

---

src/components/Game/Wordsy/Utils/helpers.js

This PR fixes the wordsy keyboard alphabet ordering, keeping the buttons sorted alphabetically instead of by length.
N/A

FW-5443 Sort wordsy keyboard alphabet order alphabetically

---

src/components/UserMenu/UserMenuPresentation.js

This PR moves the sign in/out button to the bottom of the user menu and adds a separator between the menu actions and the sign in/out button.
N/A

FW-5010 Move sign in/out to the bottom of user menu

---

src/common/dataAdaptors/dictionaryAdaptors.js
src/common/dataHooks/useImmersionLabels.js
src/components/DashboardImmersion/DashboardImmersionData.js
src/components/DashboardImmersion/ImmersionCrudForm.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js
src/components/NotificationBanner/NotificationBanner.js

- Added a warning banner on the dictionary entry edit form for entries being used as immersion labels
- Updated the immersion label edit form to delete the immersion label if the dictionary entry is removed and saved
N/A

FW-5422, FW-5483 isimmersionlabel warning banner and allow for removing labels

---

package-lock.json
package.json
src/common/dataHooks/useImmersionLabels.js
src/components/ImmersionToggle/ImmersionTogglePresentation.js
src/components/ImmersionToggle/index.js
src/components/NavBar/NavBarPresentationMobile.js
src/components/Site/SiteData.js
src/components/UserMenu/UserMenuPresentation.js
src/i18n.js

- Added i18next-browser-languagedetector to handle persistence of language selection
- fixed bug where immersion labels would carry to sites that don't have any labels
- fixed bug where immersion mode would stay on even if switched to a site without the immersion feature enabled
- Moved the immersion toggle into a reusable component
- Added immersion toggle to mobile menu and adjusted styling
N/A

FW-5472, FW-5482 immersion toggle mobile and immersion persist

---

src/components/Actions/ShareButton.js
src/components/ActionsMenu/ActionsMenuPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/DictionaryGridTile/DictionaryGridTilePresentation.js
src/components/DictionaryList/DictionaryListPresentation.js
src/components/Immersion/ImmersionPresentationList.js

- Adds a `sitename` prop to ShareButton and ActionsMenuPresentation allowing the DictionaryDetail components to pass the site name for correct QR code and share link generation.
- Passes the sitename prop to ActionsMenuPresentation in all uses for consistency
N/A

FW-5521 Fix sharebutton and qrcodebutton links

---

src/components/CategoriesBrowser/CategoriesBrowserPresentation.js
src/components/Form/CategoryArrayField.js

categories modal height reduced. Add category button only shows once a category is selected. Styling fixed so categories will scroll within modal 
N/A

Fw 4786 dashboard qol categories

---

src/common/utils/validationHelpers.js

Updates the validation regex to include short youtube links
I could also update the placeholder in the video link input to: 
"Example links: https://www.youtube.com/watch?v=A1B2C3D4E5F, https://youtu.be/A1B2C3D4E5F or https://vimeo.com/123456789"
If the team would like, but I wasn't sure if that would be unnecessary/confusing.

FW-5552 Allow short youtube links in FE validator

---

src/common/utils/wysiwygStateHelpers.js

- This PR fixes a bug in https://firstvoices.atlassian.net/browse/FW-5543 which prevented the widget form from being saved if both the "Address" and "Social media links" fields were empty.
- This is done by returning '' if a wysiwygState string is falsy in the `getJsonFromWysiwygState` constant
N/A

FW-5543 Handle empty wysiwygState string

---

src/components/AdvancedSearchOptions/AdvancedSearchOptionsPresentation.js
src/components/Alphabet/AlphabetPresentationSelected.js
src/components/Alphabet/AlphabetPresentationWidget.js
src/components/Dictionary/DictionaryPresentation.js

- Added an `entriesCount` parameter to control number of entries being displayed in AlphabetPresentationSelected component.
- Update the results count in both splashboard and dashboard to display a '+' in case there are more than 10k search results.
N/A

Fw 5555 alphabet widget fix and search results count fix

---

src/common/utils/stringHelpers.js

Adds a check for `NaN` `Date` value before processing `Intl.DateTimeFormat`
N/A

Only process date if it is not NaN

---

src/common/hooks/useSearchBoxNavigation.js
src/components/SearchSiteForm/SearchSiteFormContainer.js

Fix issue where searchParams were maintained from other pages when using top nav search e.g. Alphabet page `char`
N/A

FW-5728 Reset searchParams when using top nav search

---

src/common/RequireAuth.js
src/common/hooks/useAuthCheck.js
src/common/utils/authHelpers.js
src/components/App/AppContainer.js
src/components/Dashboard/DashboardContainer.js
src/components/Dashboard/DashboardData.js
src/components/Dashboard/DashboardPresentation.js
src/components/DashboardEdit/DashboardEditContainer.js
src/components/DashboardEdit/DashboardEditData.js
src/components/DashboardEntries/DashboardEntriesData.js
src/components/DashboardEntries/DashboardEntriesPresentationList.js
src/components/DashboardReports/DashboardReportsData.js
src/components/DeleteButton/DeleteButtonPresentation.js
src/components/ErrorHandler/ErrorHandlerData.js
src/components/Form/CategoryArrayField.js
src/components/Form/EntryArrayField.js
src/components/Form/Visibility.js
src/components/SearchDomainSelector/SearchDomainSelectorPresentation.js
src/components/SearchForm/SearchForm.js

1.     Add Word and Phrase tiles on Edit and Create pages in the dashboard for Assistants
2.     Only show edit links in the list view for entries that are team-only for Assistants.
3.     Only show the edit button on the dashboard detail view for entries that are team-only for Assistants
4.     Remove the delete button on dictionary entry forms for Assistants
5.     Restrict the visibility selector for assistants on dictionary forms and ensure it only allows team-only
N/A

FW-4828 assistants can edit team only dictionary entries

---

src/common/dataHooks/useSongs.js
src/components/DashboardEntries/DashboardEntriesPresentationList.js
src/components/Form/NextPrevious.js

- update redirects for Assistants to redirect to edit page with filter "TEAM" (after saving songs and stories)
- Add disabled buttons with tool-tips in place of edit buttons on Public and Members entries for Assistants
N/A

FW-6025, FW-6026 assistants edit team only songs and stories

---

src/components/ImageWithLightbox/ImageWithLightboxPresentation.js

limited width of description and acknowledgemen. Added margin for eas…e of readability
N/A

FW-5924-long-image-descriptions-layout

---

src/common/dataAdaptors/galleryAdaptors.js
src/common/dataAdaptors/relatedMediaAdaptors.js
src/common/dataAdaptors/siteAdaptors.js
src/common/dataHooks/useCreateUppy.js
src/common/dataHooks/useSites.js
src/common/hooks/useArrayStateManager.js
src/common/utils/mediaHelpers.js
src/components/CharacterCrud/CharacterCrudPresentation.js
src/components/DashboardJoinCard/DashboardJoinCardPresentation.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js
src/components/Form/HelpText.js
src/components/Form/ImageArrayField.js
src/components/Form/ImageIdField.js
src/components/Form/SelectOneMedia.js
src/components/Form/VideoArrayField.js
src/components/GalleryCrud/GalleryCrudPresentation.js
src/components/HomeCrud/HomeForm.js
src/components/MediaEdit/MediaEditPresentation.js
src/components/MediaThumbnail/ImageThumbnail.js
src/components/MediaThumbnail/VideoThumbnail.js
src/components/PageCrud/PageForm.js
src/components/SelectorImages/SelectorImagesContainer.js
src/components/SelectorVisualMediaGrid/SelectorVisualMediaGridPresentation.js
src/components/SongCrud/SongCrudPresentation.js
src/components/StoryCoverCrud/StoryCoverCrudPresentation.js
src/components/StoryCrud/StoryCrudPreview.js
src/components/StoryPagesCrud/StoryPageForm.js
src/components/StoryPagesCrud/StoryPagesCrudPreview.js

- Remove the need to fetch each image/video in separate api calls for thumbnails on edit forms. Achieved by maintaining media objects in state, as opposed to only ids.
- Single image fields (except widgets) switched over to use `ImageArrayField` with `maxItems={1}` by changing data adaptors
N/A

FW-6157 shared image thumbnails

---

package.json
src/common/icons/Download.js
src/common/utils/getAppUrl.js
src/components/FVApps/FVAppsData.js
src/components/FVApps/FVAppsPresentation.js
src/components/SiteLogo/LogoPresentation.js
src/components/SiteLogo/SiteLogoPresentation.js
src/components/WidgetApps/WidgetAppsPresentation.js
webpack/webpack.development.js

* extracted a LogoPresentation component that shows an arbitrary image url and alt text
* updated the main /apps page to show the app logos using the new component
* updated the app widget to use the environment-specific app URLs and logos, and to use the new component
* bonus: tweaked the cropping on the download icon
* Note: I logged a separate issue to get all pages of the site list when displaying the list of apps (currently prod only has one page, but the next site we add will spill onto a second page)
* Note: the AWS permissions don't allow app logos to be viewed locally at the moment, just a heads up if you are testing this out before that gets resolved
N/A

Fw-6208, environment-aware apps pages

---

src/components/Form/WysiwygControls/BlockStyleToolbar.js
src/components/Form/WysiwygControls/HeaderSelect.js
src/components/Form/WysiwygControls/InlineStyleToolbar.js

Draft-js treats all unrecognized blocks as unstyled, however if we need to convert the draft-js data in the future having the  block "type" explicitly set to "unstyled" will be easier to handle.
This PR changes the value for "normal" block types to "unstyled", rather than an empty string.
N/A

Wysiwyg add unstyled

---

src/components/AddMediaModalWrapper/AddMediaModalWrapper.js
src/components/DashboardJoinList/DashboardJoinListPresentation.js

1. Remove bullets displaying in Join list on Chrome
2. Remove extra scrollbar from MediaSelector - should fix square corner issue
N/A

FW-6297 Square corners on right side of selector modal

---

.github/workflows/build-frontend.yml

Tekton takes the creds of the last commit to run the pipeline and it cannot be dependant. It has to be a user. Passing a dummy commit to override dependabot creds.
N/A

Dummy commit to override dependant creds in tekton

---

src/components/Song/SongPresentation.js

- Adds the `RelatedDocumentsList` component to `SongPresentation`
N/A

FW-6453 add related documents display to songs

---

src/components/Story/StoryPresentation.js

- Adds a `RelatedDocumentsList` to `StoryPresentation` within its own LazyLoader box.
N/A

FW-5464 add document display to stories

---

src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/Song/SongPresentation.js

- Adds the missing `{entry?.relatedDocuments.length > 0 && (` checks to dictionary entries and songs
N/A

FW-6573 hide related document header if no related documents

---

src/common/dataHooks/useAudio.js
src/components/AudioCrud/AudioUploadForm.js

- Adds an error message at the top of the audio upload modal and jumps to it if audio fails to upload
- Properly sets setIsUploading(true) so that audio button displaus "Loading..."
- Bonus: renames `createJoinRequest` in audio hook to proper `createAudio`
N/A

FW-6529 add audio upload failure notification

---

src/components/DictionaryCrud/DictionaryCrudPresentation.js
src/components/Form/Visibility.js

- Moves the `defaultVisibility` check to `useEditForm`
- Removes the `resetField` code from the Visibility component
N/A

FW-6624 retain visibility state when switching steps

---

src/components/Alphabet/AlphabetPresentationSelected.js
src/components/AudioButton/AudioButton.js

Undo the splashboard button changes in the original 6620 PR for button consistency upon release.
N/A

FW-6620 Undo splashboard button changes

---

src/components/DashboardSpeakers/DashboardSpeakersPresentation.js
src/components/DashboardTable/DashboardTablePresentation.js
src/services/api/people.js

reworked Dashboard Table to allow for infinite loading. Fixed bugs in edit speakers list to load next page
N/A

FW-6400-infinite-scroll-edit-speakers-again

---

src/components/Form/WysiwygField.js
src/components/SanitizedHtml/SanitizedHtml.js

- Adds `target: '_blank'` and `rel: 'noopener noreferrer'` specifications to both wysiwygField and wysiwygBlock
N/A

FW-6197 Ensure links always open in new tab

---

src/common/utils/stringHelpers.js
src/components/Form/WysiwygField.js
src/components/SongCrud/SongCrudPresentation.js
src/components/StoryCoverCrud/StoryCoverCrudPresentation.js
src/components/StoryPagesCrud/StoryPageForm.js
src/components/WidgetCrud/WidgetFormContact.js
src/components/WidgetCrud/WidgetFormText.js
src/components/WidgetCrud/WidgetFormTextFull.js
src/components/WidgetCrud/WidgetFormTextIcons.js

- Adds functions to remove styling from HTML and format HTML properly for TipTap after removing styling
- Adds custom paste behaviour to tiptap to strip styling from pasted HTML if the toolbar does not support styling
- Inverts toolbar usage to specify when there is a toolbar rather when there is not one
N/A

FW-6670 Remove stying from html on paste

---

src/components/Actions/Copy.js
src/components/ActionsMenu/ActionsMenuPresentation.js
src/components/Alphabet/AlphabetPresentationSelected.js
src/components/AudioButton/AudioButton.js
src/components/AudioMinimal/AudioMinimalPresentation.js
src/components/ByAlphabet/ByAlphabetFilters.js
src/components/DashboardMediaDetails/DashboardMediaDetailsPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentation.js
src/components/DictionaryDetail/DictionaryDetailPresentationDrawer.js
src/components/DictionaryGridTile/DictionaryGridTilePresentation.js
src/components/DictionaryList/DictionaryListPresentation.js
src/components/Drawer/DrawerPresentation.js
src/components/Game/PhraseScrambler/PhraseScramblerPresentation.js
src/components/Immersion/ImmersionPresentationList.js
src/components/Song/SongPresentationDrawer.js
src/components/Story/StoryPresentationDrawer.js
src/components/WidgetText/WidgetTextPresentation.js
src/components/WidgetTextConcise/WidgetTextConcisePresentation.js
src/components/WidgetWordOfTheDay/WidgetWordOfTheDayPresentation.js

Converts splashboard buttons on: 
- drawers (song, story, dictionary) 
- main fv search page
- site-wide search page
- dictionary search page
- explore languages page
- categories word list page 
- detail pages (song, story, dictionary)
Additionally reworks how some action item tooltips work, and removes now-unused variables
N/A

FW-6462 Splashboard detail buttons

---

src/common/hooks/useArrayStateManager.js
src/components/AddVideoModal/AddVideoModalContainer.js

video library didn't deselect the video when you clicked and it wasn't possible to remove it at all unless you uploaded or closed the library after clicking.
**update allows selecting and deselecting**
N/A

added a fix for video select and deselect

---

src/common/utils/validationHelpers.js
src/components/DictionaryCrud/DictionaryCrudPresentation.js

Saves blank notes & more importantly saved notes with content too. (unlike my last fix)
`.compact(item ⇒ item.text.trim()==='' )` etc etc drops blank entries before validating
N/A

FW-5918 - New version of the Blank Notes Ack Problem

---

src/components/AudioCrud/AudioCrudData.js
src/services/api/people.js

- Switch over speaker select to correctly access results now that `usePeople` is returning an `infiniteQueryResponse`
- Increase perPage to tide us over till [FW-6417](https://firstvoices.atlassian.net/browse/FW-6417)
N/A
[FW-6417]: https://firstvoices.atlassian.net/browse/FW-6417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FW-6724 add speaker select fix

---

src/common/dataHooks/useCategories.js
src/common/dataHooks/useCharacters.js
src/common/dataHooks/useDictionaryEntry.js
src/common/dataHooks/useGalleries.js
src/common/dataHooks/useSongs.js
src/common/dataHooks/useStories.js

Remove check for UUID and just check that a string is present on detail pages, so as not to prevent 404s for invalid strings/ids. Applies to:
- Song
- Story
- Dictionary Entry
- Category
- Gallery
- Character
N/A

FW-5492 Remove check for UUID and just check that a string is present
